name: Trigger auto deployment for service-catalogue-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/service-catalogue-app-AutoDeployTrigger-a787c45d-f79e-41b2-a56f-57bce419dc3e.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SERVICECATALOGUEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SERVICECATALOGUEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SERVICECATALOGUEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.SERVICECATALOGUEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERVICECATALOGUEAPP_REGISTRY_PASSWORD }}
          containerAppName: service-catalogue-app
          resourceGroup: monGroupeDeRessources
          imageToBuild: ghcr.io/ismail-mouyahada/service-catalogue:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


