name: Trigger auto deployment for service-catalogue-app

on:
  push:
    branches: 
      [ main ]
    paths:
      - '**'
      - '.github/workflows/service-catalogue-app.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SERVICECATALOGUEAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SERVICECATALOGUEAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SERVICECATALOGUEAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Créer Azure Cosmos DB avec API MongoDB
        run: |
          az cosmosdb create --name myCosmosDBAccount \
                            --resource-group monGroupeDeRessources \
                            --kind MongoDB \
                            --enable-free-tier true

          # Créer la base de données MongoDB
          az cosmosdb mongodb database create \
            --account-name myCosmosDBAccount \
            --resource-group monGroupeDeRessources \
            --name mondb

      - name: Récupérer la chaîne de connexion MongoDB
        run: |
          COSMOS_CONN=$(az cosmosdb keys list \
                        --name myCosmosDBAccount \
                        --resource-group monGroupeDeRessources \
                        --type connection-strings \
                        --query "connectionStrings[0].connectionString" -o tsv)

          echo "MONGO_URI=$COSMOS_CONN" >> $GITHUB_ENV

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ghcr.io
          registryUsername: ${{ secrets.SERVICECATALOGUEAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SERVICECATALOGUEAPP_REGISTRY_PASSWORD }}
          containerAppName: service-catalogue-app
          resourceGroup: monGroupeDeRessources
          imageToBuild: ghcr.io/ismail-mouyahada/service-catalogue:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_

      - name: Injecter les variables d'environnement dans Azure Container App
        run: |
          az containerapp update \
            --name service-catalogue-app \
            --resource-group monGroupeDeRessources \
            --set-env-vars MONGO_URI=${{ env.MONGO_URI }}
